binary_sensor:
 
  - platform: ping
    host: 87.249.224.1
    count: 2
    scan_interval: 60
    name: DNS_LTK_1_is_available
  - platform: ping
    host: 92.61.16.1
    count: 2
    scan_interval: 60
    name: DNS_LTK_2_is_available
  - platform: ping
    host: 78.85.0.1
    count: 2
    scan_interval: 60
    name: DNS_RTK_1_is_available
  - platform: ping
    host: 78.85.1.1
    count: 2
    scan_interval: 60
    name: DNS_RTK_2_is_available
  - platform: ping
    host: google.com
    count: 2
    scan_interval: 60
    name: google_is_available
  - platform: ping
    host: ya.ru
    count: 2
    scan_interval: 60
    name: yandex_is_available
  - platform: ping
    host: maslenka18.ru
    count: 2
    scan_interval: 60
    name: maslenka18.ru_is_available
  - platform: ping
    host: mail.ru
    count: 2
    scan_interval: 60
    name: mail.ru_is_available
  - platform: ping
    host: catalog.mann-filter.com
    count: 2
    scan_interval: 60
    name: catalog.mann-filter.com_is_available
  - platform: ping
    host: berg.ru
    count: 2
    scan_interval: 60
    name: berg.ru_is_available
  - platform: ping
    host: izh.rossko.ru
    count: 2
    scan_interval: 60
    name: izh.rossko.ru_is_available  
  - platform: ping
    host: www.part-kom.ru
    count: 2
    scan_interval: 60
    name: www.part-kom.ru_is_available  
  - platform: ping
    host: www.mirdvornikov.ru
    count: 2
    scan_interval: 60
    name: www.mirdvornikov.ru_is_available 
  - platform: ping
    host: 192.168.10.1
    count: 2
    scan_interval: 60
    name: gateway  

  - platform: template
    sensors:
      internet_is_available:
        value_template: "{{ states('binary_sensor.google_is_available') == 'on' or states('binary_sensor.yandex_is_available') == 'on' }}"
        device_class: connectivity
        
template:
  - sensor:
      - name: "Gateway ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.gateway', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Google ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.google_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Yandex ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.yandex_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Maslenka18.ru ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.maslenka18_ru_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Mail.ru ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.mail_ru_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Catalog.mann-filter.com ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.catalog_mann_filter_com_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Berg.ru ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.berg_ru_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Izh.rossko.ru ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.izh_rossko_ru_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Part-kom.ru ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.www_part_kom_ru_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "Mirdvornikov.ru ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.www_mirdvornikov_ru_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "DNS_LTK_1 ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.DNS_LTK_1_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "DNS_LTK_2 ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.DNS_LTK_2_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "DNS_RTK_1 ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.DNS_RTK_1_is_available', 'round_trip_time_max')  }}"
  - sensor:
      - name: "DNS_RTK_2 ping time"
        unit_of_measurement: "ms"
        state: "{{ state_attr('binary_sensor.DNS_RTK_2_is_available', 'round_trip_time_max')  }}"
 